name: Sync
on: push
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SYNC }}
        with:
          source-repo: "https://github.com/jesshaw/sync.git" 
          destination-repo: "git@gitee.com:jesshaw/sync.git"